spring:
  application:
    name: vehiclesale

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  flyway:
    enabled: false

  # OAuth2/Google desativado temporariamente.
  # security:
  #   oauth2:
  #     client:
  #       registration:
  #         google:
  #           client-id: ${GOOGLE_CLIENT_ID}
  #           client-secret: ${GOOGLE_CLIENT_SECRET}

server:
  port: 8090

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

springdoc:
  override-with-generic-response-false: false

logging:
  file:
    name: app.log
  level:
    root: warn
    com:
      example: trace
    org:
      springframework:
        web: debug
