-- V1 baseline schema for PostgreSQL
-- Spec-first contract: tables and constraints aligned with current JPA model.

CREATE TABLE users (
    id UUID PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255)
);

CREATE TABLE user_roles (
    user_id UUID NOT NULL,
    role VARCHAR(255) NOT NULL,
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE TABLE customers (
    document VARCHAR(20) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    position VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE vehicles (
    vin VARCHAR(17) PRIMARY KEY,
    license_plate VARCHAR(255) NOT NULL UNIQUE,
    brand VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    color VARCHAR(255),
    model_year INTEGER NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    status VARCHAR(255) DEFAULT 'AVAILABLE',
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_vehicles_price_positive
        CHECK (price > 0),
    CONSTRAINT ck_vehicles_status
        CHECK (status IN ('AVAILABLE', 'SOLD', 'MAINTENANCE'))
);

CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_vin VARCHAR(17) NOT NULL UNIQUE,
    customer_id VARCHAR(20) NOT NULL,
    employee_id BIGINT NOT NULL,
    sale_value NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(255),
    sale_date TIMESTAMP,
    CONSTRAINT fk_sales_vehicle
        FOREIGN KEY (vehicle_vin)
        REFERENCES vehicles (vin),
    CONSTRAINT fk_sales_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers (document),
    CONSTRAINT fk_sales_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees (id),
    CONSTRAINT ck_sales_value_positive
        CHECK (sale_value > 0),
    CONSTRAINT ck_sales_payment_method
        CHECK (payment_method IS NULL OR payment_method IN ('CREDIT', 'DEBIT', 'PIX', 'BOLETO', 'CRYPTO'))
);

CREATE INDEX idx_user_roles_user_id ON user_roles (user_id);
CREATE INDEX idx_sales_customer_id ON sales (customer_id);
CREATE INDEX idx_sales_employee_id ON sales (employee_id);
